github:
  prebuilds:
    pullRequestsFromForks: true
    addComment: true
    
image: 
  file: .gitpod.Dockerfile
tasks:
  - init: ${GITPOD_REPO_ROOT}/utils/init-script.sh

vscode:
  extensions:
    -  https://github.com/microsoft/vscode-eslint/releases/download/release%2F2.1.24-Insider/vscode-eslint-2.1.24.vsix
